/**
 * NarrativeEngine: converts events + drift scores into a runtime story.
 *
 * This is the "Git Blame for Autonomous Agents" output layer.
 *
 * Input:  event stream + scored snapshots
 * Output: ordered NarrativeSegments — a human-readable session story
 *
 * Example output:
 *   T+0m   [mutation]   Human created goal: "fix login bug"
 *   T+2m   [alignment]  Agent reading auth files, aligned with goal
 *   T+9m   [drift]      Scope expansion detected: eslint upgrade introduced
 *   T+19m  [drift]      Original goal inactive for 10 minutes
 *   T+22m  [takeover]   Drift score 0.81 — human intervention recommended
 *
 * Segments are generated by classifying events against scored context.
 * The engine does NOT call an LLM. Summaries are template-based in v0.
 * LLM-generated summaries are a Phase 2 enhancement.
 */

import type { RuntimeEvent } from '../types/event'
import type { DriftScore } from '../types/scoring'
import type { Goal } from '../types/goal'
import type { NarrativeSegment, SessionNarrative, NarrativeCategory } from '../types/narrative'
import type { GoalMutation } from '../types/mutation'

function generateId(): string {
  return `seg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`
}

function minutesFrom(start: number, now: number): string {
  const m = Math.round((now - start) / 60_000)
  return `T+${m}m`
}

// ---------------------------------------------------------------------------
// Segment templates
// ---------------------------------------------------------------------------

function templateMutation(mutation: GoalMutation, goal: Goal): string {
  const actor = mutation.source === 'human' ? 'Human' : 'Agent'
  switch (mutation.mutation_type) {
    case 'refine':
      return `${actor} refined goal: "${goal.raw}"`
    case 'expand':
      return mutation.authorized
        ? `${actor} expanded goal scope: "${goal.raw}"`
        : `UNAUTHORIZED: ${actor} attempted scope expansion — "${goal.raw}"`
    case 'replace':
      return `${actor} replaced goal with: "${goal.raw}"`
    case 'cancel':
      return `${actor} cancelled goal`
  }
}

function templateGoalCreated(goal: Goal): string {
  return `Human created goal: "${goal.raw}"`
}

function templateAlignment(event: RuntimeEvent): string {
  const tool = String(event.payload['tool_name'] ?? 'action')
  const target = event.payload['target']
    ? ` on ${event.payload['target']}`
    : ''
  return `Agent executing ${tool}${target} — aligned with goal`
}

function templateDrift(score: DriftScore, signals: string[]): string {
  return `Drift score ${score.score.toFixed(2)}: ${signals.join(', ')}`
}

function templateForgotten(inactive_minutes: number): string {
  return `Original goal inactive for ${Math.round(inactive_minutes)} minutes — goal forgotten`
}

function templateTakeover(score: DriftScore): string {
  return `Drift score ${score.score.toFixed(2)} — human intervention recommended`
}

function templateExploration(event: RuntimeEvent): string {
  const tool = String(event.payload['tool_name'] ?? 'action')
  return `Agent executing ${tool} — unrelated to current goal (monitoring)`
}

// ---------------------------------------------------------------------------
// Engine
// ---------------------------------------------------------------------------

export interface ScoredSnapshot {
  event: RuntimeEvent
  score: DriftScore
}

export class NarrativeEngine {
  private segments: NarrativeSegment[] = []
  private sessionStart: number

  constructor(sessionStart: number) {
    this.sessionStart = sessionStart
  }

  /**
   * Process a new event + its drift score.
   * Appends zero or more NarrativeSegments based on what happened.
   */
  process(
    event: RuntimeEvent,
    score: DriftScore,
    context: {
      goal?: Goal | null
      mutation?: GoalMutation
      previousScore?: DriftScore
    } = {}
  ): NarrativeSegment[] {
    const newSegments: NarrativeSegment[] = []
    const time = minutesFrom(this.sessionStart, event.timestamp)

    // --- Goal created ---
    if (event.type === 'goal_created' && context.goal) {
      newSegments.push(this.makeSegment({
        session_id: event.session_id,
        timestamp:  event.timestamp,
        category:   'mutation',
        summary:    `${time}  ${templateGoalCreated(context.goal)}`,
        event_ids:  [event.id],
        score,
      }))
    }

    // --- Goal mutation ---
    if (event.type === 'goal_mutated' && context.mutation && context.goal) {
      const category: NarrativeCategory = context.mutation.authorized
        ? 'mutation'
        : 'drift'
      newSegments.push(this.makeSegment({
        session_id: event.session_id,
        timestamp:  event.timestamp,
        category,
        summary:    `${time}  ${templateMutation(context.mutation, context.goal)}`,
        event_ids:  [event.id],
        score,
      }))
    }

    // --- Tool call events ---
    if (event.type === 'tool_call') {
      const relation = event.goal_relation

      if (relation === 'aligned' || relation === 'refinement') {
        newSegments.push(this.makeSegment({
          session_id: event.session_id,
          timestamp:  event.timestamp,
          category:   'alignment',
          summary:    `${time}  ${templateAlignment(event)}`,
          event_ids:  [event.id],
          score,
        }))
      } else if (relation === 'expansion') {
        const driftSignals = this.extractDriftReasons(score)
        newSegments.push(this.makeSegment({
          session_id: event.session_id,
          timestamp:  event.timestamp,
          category:   'drift',
          summary:    `${time}  ${templateDrift(score, driftSignals)}`,
          event_ids:  [event.id],
          score,
        }))
      } else if (relation === 'unrelated') {
        newSegments.push(this.makeSegment({
          session_id: event.session_id,
          timestamp:  event.timestamp,
          category:   'exploration',
          summary:    `${time}  ${templateExploration(event)}`,
          event_ids:  [event.id],
          score,
        }))
      }
    }

    // --- Goal forgotten threshold crossed ---
    if (
      score.signals.inactive_duration_minutes >= 10 &&
      score.signals.consecutive_unrelated >= 5 &&
      !this.alreadySegmented('goal_forgotten', event.session_id)
    ) {
      newSegments.push(this.makeSegment({
        session_id: event.session_id,
        timestamp:  event.timestamp,
        category:   'drift',
        summary:    `${time}  ${templateForgotten(score.signals.inactive_duration_minutes)}`,
        event_ids:  score.contributing_event_ids,
        score,
      }))
    }

    // --- Takeover recommended ---
    const prevScore = context.previousScore?.score ?? 0
    if (score.score >= 0.75 && prevScore < 0.75) {
      newSegments.push(this.makeSegment({
        session_id: event.session_id,
        timestamp:  event.timestamp,
        category:   'takeover',
        summary:    `${time}  ${templateTakeover(score)}`,
        event_ids:  score.contributing_event_ids,
        score,
      }))
    }

    this.segments.push(...newSegments)
    return newSegments
  }

  /**
   * Build the complete session narrative.
   */
  build(session_id: string): SessionNarrative {
    const sessionSegments = this.segments.filter(s => s.session_id === session_id)

    const driftCount    = sessionSegments.filter(s => s.category === 'drift').length
    const takeoverCount = sessionSegments.filter(s => s.category === 'takeover').length
    const alignCount    = sessionSegments.filter(s => s.category === 'alignment').length

    let overall: string
    if (takeoverCount > 0) {
      overall = `Session drifted and required human intervention. ${driftCount} drift event(s) detected across ${sessionSegments.length} narrative segments.`
    } else if (driftCount > 0) {
      overall = `Session showed drift signals (${driftCount} event(s)) but remained below takeover threshold.`
    } else {
      overall = `Session stayed aligned with goal throughout. ${alignCount} aligned action(s) recorded.`
    }

    return {
      session_id,
      generated_at: Date.now(),
      segments: sessionSegments,
      overall_summary: overall,
    }
  }

  getSegments(): NarrativeSegment[] {
    return [...this.segments]
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  private makeSegment(params: {
    session_id: string
    timestamp: number
    category: NarrativeCategory
    summary: string
    event_ids: string[]
    score: DriftScore
  }): NarrativeSegment {
    return {
      id:                   generateId(),
      session_id:           params.session_id,
      timestamp:            params.timestamp,
      category:             params.category,
      summary:              params.summary,
      supporting_event_ids: params.event_ids,
      drift_score_at_time:  params.score.score,
    }
  }

  private extractDriftReasons(score: DriftScore): string[] {
    const reasons: string[] = []
    const s = score.signals
    if (s.semantic_divergence > 0.6)        reasons.push('actions diverging from goal')
    if (s.consecutive_unrelated >= 3)       reasons.push(`${s.consecutive_unrelated} consecutive unrelated actions`)
    if (s.inactive_duration_minutes >= 5)   reasons.push(`goal inactive ${Math.round(s.inactive_duration_minutes)}m`)
    if (s.subgoal_depth >= 3)               reasons.push(`subgoal depth ${Math.round(s.subgoal_depth * 3)}`)
    if (s.unauthorized_mutations > 0)       reasons.push(`${s.unauthorized_mutations} unauthorized mutation(s)`)
    return reasons.length > 0 ? reasons : ['drift threshold crossed']
  }

  private alreadySegmented(type: string, session_id: string): boolean {
    // Prevent duplicate "goal forgotten" segments per session
    if (type === 'goal_forgotten') {
      return this.segments.some(
        s => s.session_id === session_id &&
             s.category === 'drift' &&
             s.summary.includes('inactive for')
      )
    }
    return false
  }
}